#!/bin/bash
sudo -i
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
sudo echo deb https://apt.dockerproject.org/repo ubuntu-trusty main >> /etc/apt/sources.list.d/docker.list
sudo apt-get update
sudo apt-get install -y docker-engine
sudo service docker start
T_IP=$(echo `ifconfig eth0 2>/dev/null|awk '/inet addr:/ {print $2}'|sed 's/addr://'`)

docker run -d \
-e MESOS_HOSTNAME=mesos-master \
-e MESOS_IP=$HOST_IP \
-e MESOS_QUORUM=2 \
-e MESOS_ZK=zk://node-1:2181,node-2:2181,node-3:2181/mesos \
--name mesos-master --net host --restart always mesoscloud/mesos-master:0.24.1-ubuntu-14.04

docker run -d \
  -e SERVER_ID=1 \
  -e ADDITIONAL_ZOOKEEPER_1=server.1=1.1.1.1:2888:3888 \
  -e ADDITIONAL_ZOOKEEPER_2=server.2=1.1.1.1:2888:3888 \
  -e ADDITIONAL_ZOOKEEPER_3=server.3=1.1.1.1:2888:3888 \
  -p 2181:2181 \
  -p 2888:2888 \
  -p 3888:3888 \
  garland/zookeeper

docker run --net="host" \
  -p 5050:5050 \
  -e "MESOS_HOSTNAME=${HOST_IP}" \
  -e "MESOS_IP=${HOST_IP}" \
  -e "MESOS_ZK=zk://${HOST_IP}:2181/mesos" \
  -e "MESOS_PORT=5050" \
  -e "MESOS_LOG_DIR=/var/log/mesos" \
  -e "MESOS_QUORUM=1" \
  -e "MESOS_REGISTRY=in_memory" \
  -e "MESOS_WORK_DIR=/var/lib/mesos" \
  -d \
  garland/mesosphere-docker-mesos-master

  docker run \
 -d \
 -p 8080:8080 \
 garland/mesosphere-docker-marathon --master zk://${HOST_IP}:2181/mesos --zk zk://${HOST_IP}:2181/marathon

  docker run -d \
 --entrypoint="mesos-slave" \
 -e "MESOS_MASTER=zk://${HOST_IP}:2181/mesos" \
 -e "MESOS_LOG_DIR=/var/log/mesos" \
 -e "MESOS_LOGGING_LEVEL=INFO" \
 garland/mesosphere-docker-mesos-master:latest
exit 0
